---

#
# Define automatically applied labels
#

github:
  - ".github/**"

documentation:
  - "**.md"
  - "**.cff"

citation:
  - "**.cff"

chore:
  - "**.gitignore"
  - "**.gitattributes"

test:
  - "**/test/**"
  - "**/tests/**"
  - "**_test.*"
