#
# Configure the OctoCov tool
#
# See: https://github.com/k1LoW/octocov#configuration
#

---

repository: norwd/pword

coverage:

  paths:
    - ../coverage.out

  badge:
    path: assets/coverage.svg

push:
  if: is_pull_request

report:
  datastores:
    - artifact://norwd/pword
