---

name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'

  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

  - title: '🧰 Maintenance'
    labels:
      - 'chore'

  - title: '⬆️ Dependencies'
    collapse-after: 3
    labels:
      - 'dependencies'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

replacers:
  - search: '@norwd'
    replace: 'norwd'

version-resolver:
  default: patch

  major:
    labels:
      - 'major'

  minor:
    labels:
      - 'minor'

  patch:
    labels:
      - 'patch'

template: |
  ## Changes

  $CHANGES

  ## Thanks

  $CONTRIBUTORS
