---

prerelease: true

name-template: 'v$RESOLVED_VERSION ðŸŒˆ'
tag-template: 'v$RESOLVED_VERSION'

change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&'

categories:
  - title: 'ðŸš€ Features'
    labels:
      - 'feature'
      - 'enhancement'

  - title: 'ðŸ› Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

  - title: 'ðŸ§° Maintenance'
    labels:
      - 'chore'

  - title: 'â¬†ï¸ Dependencies'
    collapse-after: 3
    labels:
      - 'dependencies'

version-resolver:
  default: patch

  major:
    labels:
      - 'major'

  minor:
    labels:
      - 'minor'

  patch:
    labels:
      - 'patch'

template: |
  ## Changes

  $CHANGES

  ## Thanks

  $CONTRIBUTORS
