---

name: "Enable Automerge"
run-name: "Automerge enabled for #${{ github.event.number }}"
permissions:
  pull-requests: write
  contents: write

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - ready_for_review

defaults:
  run:
    shell: bash

jobs:
  automerge:
    name: Enable Automerge
    runs-on: ubuntu-latest
    steps:
      - name: Enable Automerge
        run: gh -R ${{ github.repository }} pr merge ${{ github.event.number }} --auto --merge
        env:
          GH_TOKEN: ${{ secrets.AUTO_MERGE_PWORD || secrets.GITHUB_TOKEN }}
