---

name: "Go"
run-name: "Go workflow started by @${{ github.actor }}"
permissions: read-all

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: Jerome1337/golint-action@v1.0.2
        with:
          golint-path: '.'

  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-go@v3
        with:
          stable: false
          go-version: '^1'

      - run: go vet

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-go@v3
        with:
          stable: false
          go-version: '^1'

      - run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-go@v3
        with:
          stable: false
          go-version: '^1'

      - run: go test -v ./...

  fmt:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          token: ${{ secrets.AUTO_GO_FMT_PWORD || secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}

      - uses: actions/setup-go@v3
        with:
          go-version: '^1'

      - run: go fmt -x

      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: gofmt

  report:
    runs-on: ubuntu-latest
    steps:
      - uses: creekorful/goreportcard-action@v1.0
