---

name: "Go"
run-name: "Go workflow started by @${{ github.actor }}"
permissions: read-all

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Jerome1337/golint-action@v1.0.2
        with:
          golint-path: '.'

  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          stable: false
          go-version: '^1'

      - run: go vet

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          stable: false
          go-version: '^1'

      - run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          stable: false
          go-version: '^1'

      - run: go test -v ./...

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTO_GO_FMT_PWORD || secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}

      - uses: actions/setup-go@v3
        with:
          go-version: '^1'

      - run: gofmt -l -w -s ./...

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto go-fmt

  report:
    runs-on: ubuntu-latest
    steps:
      - uses: creekorful/goreportcard-action@v1.0
