---

name: "Issue Development"
run-name: "Starting Pull Request for #${{ github.event.issue.number }}"
permissions:
  issues: write

on:
  issues:
    types:
      - opened
      - reopened

defaults:
  run:
    shell: bash

jobs:
  branch_and_open_pr:
    name: "Creating Development Branch and PR"
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ISSUE_ID: ${{ github.event.issue.number }}
      PR_TITLE: ${{ github.event.issue.title }}
      PR_DESCR: |
        # ${{ github.event.title }}

        Closes #${{ github.event.number }}
    steps:
      - name: "Check `gh` version"
        run: |
          gh version

      - name: "Install gh tool"
        run: |
          type -p curl >/dev/null || sudo apt install curl -y
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      - name: "Check `gh` version again"
        run: |
          gh version

      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Create and Checkout branch"
        run: |
          gh issue develop --base "$GITHUB_REF" --checkout "$ISSUE_ID"

      - name: "Create and Draft pr"
        run: |
          gh pr create --draft --assignee "${{ github.actor }}" --base "$GITHUB_REF" --title "$PR_TITLE" --body "$PR_DESCR"
