---

name: "Lint"
run-name: "Linters started by @${{ github.actor }}"
permissions: read-all

on:
  push:

jobs:

  # Lint all workflow actions
  actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-actionlint@v1
        with:
          fail_on_error: true

  # Lint all *.md files
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: nosborn/github-action-markdown-cli@v3.2.0
        with:
          files: "**/*.md"
          dot: true

  # Lint all .yml files
  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ibiqlik/action-yamllint@v3
        with:
          strict: true
          format: parsable
          config_data: |
            extends: default
            rules:
              line-length: disable
              truthy:
                check-keys: false
                allowed-values:
                  - "true"
                  - "false"

  # Check all files against the .editorconfig
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: editorconfig-checker/action-editorconfig-checker@v1.0.0
