---

name: "Release Assets"
run-name: "Release Asset workflow started by @${{ github.actor }}"
permissions: read-all

on:
  release:
    types: [created]

defaults:
  run:
    shell: bash

concurrency:
  group: release
  cancel-in-progress: true

jobs:

  release-assets:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ['linux', 'windows', 'darwin']
        goarch: ['386', 'amd64', 'arm64']
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release ${{ matrix.goos }}/${{ matrix.goarch }}
        uses: wangyoucao577/go-release-action@v1.33
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          extra_files: LICENSE README.md CITATION.cff
          md5sum: false
          sha256sum: true
